name: Mobile Preview Deploy

on:
  workflow_dispatch:
    inputs:
      REQUEST_ID:
        description: 'Request ID'
        required: true
      AZURE_PROJECT_NAME:
        description: 'Azure DevOps project name'
        required: true
      AZURE_REPO_NAMES:
        description: 'Comma-separated list of Azure repo names'
        required: true
      GCS_BUCKET_NAME:
        description: 'Google Cloud Storage bucket name'
        required: true

jobs:
  mobile-preview-deploy:
    runs-on: macos-15
    env:
      REQUEST_ID: ${{ github.event.inputs.REQUEST_ID }}
      AZURE_PROJECT_NAME: ${{ github.event.inputs.AZURE_PROJECT_NAME }}
      AZURE_REPO_NAMES: ${{ github.event.inputs.AZURE_REPO_NAMES }}
      AZURE_PAT: ${{ secrets.AZURE_PAT }}
      GCS_BUCKET_NAME: ${{ github.event.inputs.GCS_BUCKET_NAME }}
      OPERATION: mobilePreviewDeploy

    steps:
      # ------------------------ Git ------------------------
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ------------------------ Python ------------------------
      - name: Set up Python 3.12.0
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'

      - name: Install Python Dependencies
        run: |
          pip install -r requirement.txt

      # ------------------------ Flutter ------------------------
      - name: Set up Flutter 3.29.2
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      - name: Install Flutter Dependencies
        run: flutter pub get

      # ------------------------ Firebase CLI ------------------------
      - name: Install Firebase CLI via npm
        run: |
          if ! command -v firebase &> /dev/null; then
            echo "Installing Firebase CLI with npm..."
            npm install -g firebase-tools
          else
            echo "Firebase CLI already installed"
          fi

      # ------------------------ Run Python Script ------------------------
      # - name: Execute mobilePreviewDeploy
      #   run: python functions/src/docker/flutter-operations/flutter_operations.py
