name: Mobile Preview Deploy

on:
  workflow_dispatch:
    inputs:
      requestId:
        description: 'Request ID'
        required: true
      azureProjectName:
        description: 'Azure DevOps project name'
        required: true
      azureRepoNames:
        description: 'Comma-separated list of Azure repo names'
        required: true
      gcsBucketName:
        description: 'Google Cloud Storage bucket name'
        required: true

jobs:
  mobile-preview-deploy:
    runs-on: macos-15
    env:
      REQUEST_ID: ${{ github.event.inputs.requestId }}
      AZURE_PROJECT_NAME: ${{ github.event.inputs.azureProjectName }}
      AZURE_REPO_NAMES: ${{ github.event.inputs.azureRepoNames }}
      AZURE_PAT: ${{ secrets.AZURE_PAT }}
      GCS_BUCKET_NAME: ${{ github.event.inputs.gcsBucketName }}
      OPERATION: mobilePreviewDeploy

    steps:
      # ------------------------ Git ------------------------
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ------------------------ Python ------------------------
      - name: Set up Python 3.12.0
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'

      - name: Install Python Dependencies
        run: |
          pip install -r requirement.txt

      # ------------------------ Flutter ------------------------
      - name: Set up Flutter 3.29.2
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      - name: Install Flutter Dependencies
        run: flutter pub get

      # ------------------------ Firebase CLI ------------------------
      - name: Install Firebase CLI via npm
        run: |
          if ! command -v firebase &> /dev/null; then
            echo "Installing Firebase CLI with npm..."
            npm install -g firebase-tools
          else
            echo "Firebase CLI already installed"
          fi
          
      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      # ------------------------ Run Python Script ------------------------
      - name: Execute mobilePreviewDeploy
        run: python flutter_operations.py

      # ------------------------ Upload to Artifact ------------------------
      - name: Upload artifact log file
        uses: actions/upload-artifact@v3
        with:
          name: mobile-preview-log
          path: /tmp/workspaces/artifact_logs.log
