name: Mobile Preview Deploy

on:
  workflow_dispatch:
    inputs:
      REQUEST_ID:
        description: 'Request ID'
        required: true
      AZURE_PROJECT_NAME:
        description: 'Azure DevOps project name'
        required: true
      AZURE_REPO_NAMES:
        description: 'Comma-separated list of Azure repo names'
        required: true
      GCS_BUCKET_NAME:
        description: 'Google Cloud Storage bucket name'
        required: true

jobs:
  mobile-preview-deploy:
    runs-on: macos-15
    env:
      REQUEST_ID: ${{ github.event.inputs.REQUEST_ID }}
      AZURE_PROJECT_NAME: ${{ github.event.inputs.AZURE_PROJECT_NAME }}
      AZURE_REPO_NAMES: ${{ github.event.inputs.AZURE_REPO_NAMES }}
      AZURE_PAT: ${{ secrets.AZURE_PAT }}
      GCS_BUCKET_NAME: ${{ github.event.inputs.GCS_BUCKET_NAME }}
      OPERATION: mobilePreviewDeploy
      FLUTTER_HOME: ~/.flutter

    steps:
      # ------------------------ Git ------------------------
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ------------------------ Python ------------------------
      - name: Set up Python 3.12.0
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'

      - name: Install Python Dependencies
        run: |
          pip install -r requirement.txt

      # ------------------------ Flutter ------------------------
      - name: Create Flutter Version File
        run: echo "3.29.2" > flutter_version.txt


      - name: Cache Flutter SDK
        id: flutter-cache
        uses: actions/cache@v3
        with:
          path: ~/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('flutter_version.txt') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install Flutter if not cached
        if: steps.flutter-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/flutter/flutter.git -b 3.29.2 ~/.flutter

      - name: Add Flutter to PATH
        run: echo "$HOME/.flutter/bin" >> $GITHUB_PATH

      - name: Cache Pub Packages
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install Pub Packages
        run: flutter pub get
        

      # ------------------------ Firebase CLI ------------------------
      - name: Cache Firebase CLI
        uses: actions/cache@v3
        with:
          path: ~/.cache/firebase
          key: ${{ runner.os }}-firebase-cli
          restore-keys: |
            ${{ runner.os }}-firebase-cli

      - name: Install Firebase CLI via npm
        run: |
          if ! command -v firebase &> /dev/null; then
            echo "Installing Firebase CLI with npm..."
            npm install -g firebase-tools
          else
            echo "Firebase CLI already installed"
          fi

      # ------------------------ Run Python Script ------------------------
      # - name: Execute mobilePreviewDeploy
      #   run: python functions/src/docker/flutter-operations/flutter_operations.py
